import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar";
import { Roboto_Flex } from "next/font/google";
import FooterComponent from "@/components/footer";

const behindTheNineties = localFont({
  preload: true,
  src: "./fonts/Behind-The-Nineties-Smbd.woff",
  variable: "--font-behind-the-nineties",
  weight: "600",
});
const robotoFlex = Roboto_Flex({
  preload: true,
  subsets: ["latin"],
  variable: "--font-roboto-flex",
  weight: ["400", "600", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${behindTheNineties.variable} ${robotoFlex.variable} antialiased`}
      >
        <Navbar />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
